volumes:
  mysql_data:
services:
  redis:
    image: 'redis:alpine'
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
  mysql:
    image: 'mysql:8.0'
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    volumes:
      - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
    ports:
      - '33063:3306'
  nginx:
    image: 'nginx:alpine'
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: always
    working_dir: /app
    volumes:
      - '.:/app'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8083:80'
  php:
    tty: true
    build: 
      dockerfile: docker/php/Dockerfile
      context: .
    container_name: ${COMPOSE_PROJECT_NAME}_php 
    restart: always
    working_dir: /app
    volumes:
      - '.:/app'
      - '.docker//php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
    environment:
      PHP_IDE_CONFIG: 'serverName=${COMPOSE_PROJECT_NAME}-server'
